apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websample-ing
spec:
  rules:
  - host: mysite.com
    http:
      paths:
      - backend:
          service:
            name: websample
            port: 
              number: 5000
        pathType: Prefix
        path: /